// src/constants.ts

export const EPSILON = 1e-6;

export const LAYOUT = {
  DEFAULT_COLOR: "black",
  DEFAULT_BACKGROUND: "white",
  DEFAULT_FONT_SIZE: 16, // px
  DEFAULT_STROKE_WIDTH: 1.5,

  DEFAULT_OFFSET: 5,
  AXIS_TICK_LENGTH: 8,
  AXIS_NUMBER_OFFSET: 5,
  AXIS_TITLE_EXTRA_GAP: 10,
  AXIS_LABEL_OFFSET: 10,
  CHART_TITLE_GAP: 15,
  DEFAULT_NO_NUM_OFFSET: 20,
  ARROW_SIZE: 10,
  ARROW_ANGLE: Math.PI / 6,
  ROTATION_ARROW_OFFSET: 30,
  DEFAULT_AXIS_EXTEND_START: 25,
  DEFAULT_AXIS_EXTEND_END: 30,
  DEFAULT_AXIS_STEP: 1,
  DEFAULT_AXIS_LABEL_STEP: 1,
  DEFAULT_AXIS_DOMAIN: [-5, 5] as [number, number],

  DEFAULT_PATTERN_FILL_TYPE: "diagonal",
  DEFAULT_HATCH_SPACING: 6,
  DEFAULT_HATCH_ANGLE: 45,
  DEFAULT_HATCH_COLOR: "#333",
  DEFAULT_HATCH_BACKGROUND: "transparent",
  DEFAULT_WAVE_AMPLITUDE: -2,
  DEFAULT_WAVE_LENGTH: 10,
  DEFAULT_WAVE_SPACING: 2,
  DEFAULT_WAVE_DASH: "14 2",
  DEFAULT_WAVE_STROKE_WIDTH: 1.5,

  DEFAULT_CARTESIAN_ORIGIN_LABEL_TEXT: "O",
  DEFAULT_CARTESIAN_ORIGIN_LABEL_OFFSET: 5,
  DEFAULT_CARTESIAN_ORIGIN_LABEL_ALIGN: "bottom-left",

  DEFAULT_AXIS_LABEL_OFFSET: 10,
  DEFAULT_AXIS_LABEL_ROTATION: 0,
  DEFAULT_AXIS_LABEL_FONT_SIZE: 16,
  DEFAULT_AXIS_TICK_LENGTH: 8,
  DEFAULT_AXIS_NUMBER_OFFSET: 5,
  DEFAULT_X_AXIS_LABEL_TEXT: "x",
  DEFAULT_X_AXIS_LABEL_ALIGN: "bottom",

  DEFAULT_FUNCTION_GRAPH_SAMPLES: 100,
};
